// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// get_covariance_matrices_cc
Rcpp::List get_covariance_matrices_cc(const arma::vec& y_vector, const arma::mat& model_matrix, const arma::vec& id_vector, const arma::vec& repeated_vector, const arma::vec& weights_vector, const char* link, const char* family, const arma::vec& mu_vector, const arma::vec& eta_vector, const char* correlation_structure, const arma::vec& alpha_vector, const double& phi);
RcppExport SEXP _geer_get_covariance_matrices_cc(SEXP y_vectorSEXP, SEXP model_matrixSEXP, SEXP id_vectorSEXP, SEXP repeated_vectorSEXP, SEXP weights_vectorSEXP, SEXP linkSEXP, SEXP familySEXP, SEXP mu_vectorSEXP, SEXP eta_vectorSEXP, SEXP correlation_structureSEXP, SEXP alpha_vectorSEXP, SEXP phiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y_vector(y_vectorSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type model_matrix(model_matrixSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type id_vector(id_vectorSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type repeated_vector(repeated_vectorSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weights_vector(weights_vectorSEXP);
    Rcpp::traits::input_parameter< const char* >::type link(linkSEXP);
    Rcpp::traits::input_parameter< const char* >::type family(familySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mu_vector(mu_vectorSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type eta_vector(eta_vectorSEXP);
    Rcpp::traits::input_parameter< const char* >::type correlation_structure(correlation_structureSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type alpha_vector(alpha_vectorSEXP);
    Rcpp::traits::input_parameter< const double& >::type phi(phiSEXP);
    rcpp_result_gen = Rcpp::wrap(get_covariance_matrices_cc(y_vector, model_matrix, id_vector, repeated_vector, weights_vector, link, family, mu_vector, eta_vector, correlation_structure, alpha_vector, phi));
    return rcpp_result_gen;
END_RCPP
}
// get_covariance_matrices_or
Rcpp::List get_covariance_matrices_or(const arma::vec& y_vector, const arma::mat& model_matrix, const arma::vec& id_vector, const arma::vec& repeated_vector, const arma::vec& weights_vector, const char* link, const arma::vec& mu_vector, const arma::vec& eta_vector, const arma::vec& alpha_vector);
RcppExport SEXP _geer_get_covariance_matrices_or(SEXP y_vectorSEXP, SEXP model_matrixSEXP, SEXP id_vectorSEXP, SEXP repeated_vectorSEXP, SEXP weights_vectorSEXP, SEXP linkSEXP, SEXP mu_vectorSEXP, SEXP eta_vectorSEXP, SEXP alpha_vectorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y_vector(y_vectorSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type model_matrix(model_matrixSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type id_vector(id_vectorSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type repeated_vector(repeated_vectorSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weights_vector(weights_vectorSEXP);
    Rcpp::traits::input_parameter< const char* >::type link(linkSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mu_vector(mu_vectorSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type eta_vector(eta_vectorSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type alpha_vector(alpha_vectorSEXP);
    rcpp_result_gen = Rcpp::wrap(get_covariance_matrices_or(y_vector, model_matrix, id_vector, repeated_vector, weights_vector, link, mu_vector, eta_vector, alpha_vector));
    return rcpp_result_gen;
END_RCPP
}
// fit_geesolver_cc
Rcpp::List fit_geesolver_cc(const arma::vec& y_vector, const arma::mat& model_matrix, const arma::vec& id_vector, const arma::vec& repeated_vector, const arma::vec& weights_vector, const char* link, const char* family, arma::vec beta_vector, const arma::vec& offset, const int& maxiter, const double& tolerance, const int& step_maxiter, const int& step_multiplier, const double& jeffreys_power, const char* method, int use_params, arma::vec alpha_vector, const int& alpha_fixed, const char* correlation_structure, const int& mdependence, double phi, const int& phi_fixed);
RcppExport SEXP _geer_fit_geesolver_cc(SEXP y_vectorSEXP, SEXP model_matrixSEXP, SEXP id_vectorSEXP, SEXP repeated_vectorSEXP, SEXP weights_vectorSEXP, SEXP linkSEXP, SEXP familySEXP, SEXP beta_vectorSEXP, SEXP offsetSEXP, SEXP maxiterSEXP, SEXP toleranceSEXP, SEXP step_maxiterSEXP, SEXP step_multiplierSEXP, SEXP jeffreys_powerSEXP, SEXP methodSEXP, SEXP use_paramsSEXP, SEXP alpha_vectorSEXP, SEXP alpha_fixedSEXP, SEXP correlation_structureSEXP, SEXP mdependenceSEXP, SEXP phiSEXP, SEXP phi_fixedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y_vector(y_vectorSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type model_matrix(model_matrixSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type id_vector(id_vectorSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type repeated_vector(repeated_vectorSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weights_vector(weights_vectorSEXP);
    Rcpp::traits::input_parameter< const char* >::type link(linkSEXP);
    Rcpp::traits::input_parameter< const char* >::type family(familySEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta_vector(beta_vectorSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< const int& >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< const double& >::type tolerance(toleranceSEXP);
    Rcpp::traits::input_parameter< const int& >::type step_maxiter(step_maxiterSEXP);
    Rcpp::traits::input_parameter< const int& >::type step_multiplier(step_multiplierSEXP);
    Rcpp::traits::input_parameter< const double& >::type jeffreys_power(jeffreys_powerSEXP);
    Rcpp::traits::input_parameter< const char* >::type method(methodSEXP);
    Rcpp::traits::input_parameter< int >::type use_params(use_paramsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type alpha_vector(alpha_vectorSEXP);
    Rcpp::traits::input_parameter< const int& >::type alpha_fixed(alpha_fixedSEXP);
    Rcpp::traits::input_parameter< const char* >::type correlation_structure(correlation_structureSEXP);
    Rcpp::traits::input_parameter< const int& >::type mdependence(mdependenceSEXP);
    Rcpp::traits::input_parameter< double >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const int& >::type phi_fixed(phi_fixedSEXP);
    rcpp_result_gen = Rcpp::wrap(fit_geesolver_cc(y_vector, model_matrix, id_vector, repeated_vector, weights_vector, link, family, beta_vector, offset, maxiter, tolerance, step_maxiter, step_multiplier, jeffreys_power, method, use_params, alpha_vector, alpha_fixed, correlation_structure, mdependence, phi, phi_fixed));
    return rcpp_result_gen;
END_RCPP
}
// fit_bingee_or
Rcpp::List fit_bingee_or(const arma::vec& y_vector, const arma::mat& model_matrix, const arma::vec& id_vector, const arma::vec& repeated_vector, const arma::vec& weights_vector, const char* link, arma::vec beta_vector, const arma::vec& offset, const int& maxiter, const double& tolerance, const int& step_maxiter, const int& step_multiplier, const double& jeffreys_power, const char* method, const arma::vec& alpha_vector);
RcppExport SEXP _geer_fit_bingee_or(SEXP y_vectorSEXP, SEXP model_matrixSEXP, SEXP id_vectorSEXP, SEXP repeated_vectorSEXP, SEXP weights_vectorSEXP, SEXP linkSEXP, SEXP beta_vectorSEXP, SEXP offsetSEXP, SEXP maxiterSEXP, SEXP toleranceSEXP, SEXP step_maxiterSEXP, SEXP step_multiplierSEXP, SEXP jeffreys_powerSEXP, SEXP methodSEXP, SEXP alpha_vectorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y_vector(y_vectorSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type model_matrix(model_matrixSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type id_vector(id_vectorSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type repeated_vector(repeated_vectorSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weights_vector(weights_vectorSEXP);
    Rcpp::traits::input_parameter< const char* >::type link(linkSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta_vector(beta_vectorSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< const int& >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< const double& >::type tolerance(toleranceSEXP);
    Rcpp::traits::input_parameter< const int& >::type step_maxiter(step_maxiterSEXP);
    Rcpp::traits::input_parameter< const int& >::type step_multiplier(step_multiplierSEXP);
    Rcpp::traits::input_parameter< const double& >::type jeffreys_power(jeffreys_powerSEXP);
    Rcpp::traits::input_parameter< const char* >::type method(methodSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type alpha_vector(alpha_vectorSEXP);
    rcpp_result_gen = Rcpp::wrap(fit_bingee_or(y_vector, model_matrix, id_vector, repeated_vector, weights_vector, link, beta_vector, offset, maxiter, tolerance, step_maxiter, step_multiplier, jeffreys_power, method, alpha_vector));
    return rcpp_result_gen;
END_RCPP
}
// get_naive_matrix_inverse_independence
arma::mat get_naive_matrix_inverse_independence(const arma::vec& y_vector, const arma::mat& model_matrix, const arma::vec& id_vector, const char* link, const char* family, const arma::vec& mu_vector, const arma::vec& eta_vector, const double& phi, const arma::vec& weights_vector);
RcppExport SEXP _geer_get_naive_matrix_inverse_independence(SEXP y_vectorSEXP, SEXP model_matrixSEXP, SEXP id_vectorSEXP, SEXP linkSEXP, SEXP familySEXP, SEXP mu_vectorSEXP, SEXP eta_vectorSEXP, SEXP phiSEXP, SEXP weights_vectorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y_vector(y_vectorSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type model_matrix(model_matrixSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type id_vector(id_vectorSEXP);
    Rcpp::traits::input_parameter< const char* >::type link(linkSEXP);
    Rcpp::traits::input_parameter< const char* >::type family(familySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mu_vector(mu_vectorSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type eta_vector(eta_vectorSEXP);
    Rcpp::traits::input_parameter< const double& >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weights_vector(weights_vectorSEXP);
    rcpp_result_gen = Rcpp::wrap(get_naive_matrix_inverse_independence(y_vector, model_matrix, id_vector, link, family, mu_vector, eta_vector, phi, weights_vector));
    return rcpp_result_gen;
END_RCPP
}
// get_gee_criteria_sc_cw
Rcpp::List get_gee_criteria_sc_cw(const arma::vec& y_vector, const arma::vec& id_vector, const arma::vec& repeated_vector, const char* family, const arma::vec& mu_vector, const char* correlation_structure, const arma::vec& alpha_vector, const double& phi, const arma::vec& weights_vector);
RcppExport SEXP _geer_get_gee_criteria_sc_cw(SEXP y_vectorSEXP, SEXP id_vectorSEXP, SEXP repeated_vectorSEXP, SEXP familySEXP, SEXP mu_vectorSEXP, SEXP correlation_structureSEXP, SEXP alpha_vectorSEXP, SEXP phiSEXP, SEXP weights_vectorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y_vector(y_vectorSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type id_vector(id_vectorSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type repeated_vector(repeated_vectorSEXP);
    Rcpp::traits::input_parameter< const char* >::type family(familySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mu_vector(mu_vectorSEXP);
    Rcpp::traits::input_parameter< const char* >::type correlation_structure(correlation_structureSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type alpha_vector(alpha_vectorSEXP);
    Rcpp::traits::input_parameter< const double& >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weights_vector(weights_vectorSEXP);
    rcpp_result_gen = Rcpp::wrap(get_gee_criteria_sc_cw(y_vector, id_vector, repeated_vector, family, mu_vector, correlation_structure, alpha_vector, phi, weights_vector));
    return rcpp_result_gen;
END_RCPP
}
// get_gee_criteria_sc_cw_or
Rcpp::List get_gee_criteria_sc_cw_or(const arma::vec& y_vector, const arma::vec& id_vector, const arma::vec& repeated_vector, const arma::vec& mu_vector, const arma::vec& alpha_vector, const arma::vec& weights_vector);
RcppExport SEXP _geer_get_gee_criteria_sc_cw_or(SEXP y_vectorSEXP, SEXP id_vectorSEXP, SEXP repeated_vectorSEXP, SEXP mu_vectorSEXP, SEXP alpha_vectorSEXP, SEXP weights_vectorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y_vector(y_vectorSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type id_vector(id_vectorSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type repeated_vector(repeated_vectorSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mu_vector(mu_vectorSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type alpha_vector(alpha_vectorSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weights_vector(weights_vectorSEXP);
    rcpp_result_gen = Rcpp::wrap(get_gee_criteria_sc_cw_or(y_vector, id_vector, repeated_vector, mu_vector, alpha_vector, weights_vector));
    return rcpp_result_gen;
END_RCPP
}
// get_pearson_residuals
arma::vec get_pearson_residuals(const char* family, const arma::vec& y_vector, const arma::vec& mu_vector, const arma::vec& weights_vector);
RcppExport SEXP _geer_get_pearson_residuals(SEXP familySEXP, SEXP y_vectorSEXP, SEXP mu_vectorSEXP, SEXP weights_vectorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const char* >::type family(familySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y_vector(y_vectorSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mu_vector(mu_vectorSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weights_vector(weights_vectorSEXP);
    rcpp_result_gen = Rcpp::wrap(get_pearson_residuals(family, y_vector, mu_vector, weights_vector));
    return rcpp_result_gen;
END_RCPP
}
// get_correlation_matrix
arma::mat get_correlation_matrix(const char* correlation_structure, const arma::vec& alpha_vector, const arma::uword dimension);
RcppExport SEXP _geer_get_correlation_matrix(SEXP correlation_structureSEXP, SEXP alpha_vectorSEXP, SEXP dimensionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const char* >::type correlation_structure(correlation_structureSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type alpha_vector(alpha_vectorSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type dimension(dimensionSEXP);
    rcpp_result_gen = Rcpp::wrap(get_correlation_matrix(correlation_structure, alpha_vector, dimension));
    return rcpp_result_gen;
END_RCPP
}
// get_marginalized_odds_ratios
Rcpp::NumericVector get_marginalized_odds_ratios(const arma::vec& response_vector, const arma::vec& id_vector, const arma::vec& repeated_vector, const arma::vec& weights_vector, const double& adding_constant, const Rcpp::String& or_structure);
RcppExport SEXP _geer_get_marginalized_odds_ratios(SEXP response_vectorSEXP, SEXP id_vectorSEXP, SEXP repeated_vectorSEXP, SEXP weights_vectorSEXP, SEXP adding_constantSEXP, SEXP or_structureSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type response_vector(response_vectorSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type id_vector(id_vectorSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type repeated_vector(repeated_vectorSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weights_vector(weights_vectorSEXP);
    Rcpp::traits::input_parameter< const double& >::type adding_constant(adding_constantSEXP);
    Rcpp::traits::input_parameter< const Rcpp::String& >::type or_structure(or_structureSEXP);
    rcpp_result_gen = Rcpp::wrap(get_marginalized_odds_ratios(response_vector, id_vector, repeated_vector, weights_vector, adding_constant, or_structure));
    return rcpp_result_gen;
END_RCPP
}
// estimating_equations_gee_cc
arma::vec estimating_equations_gee_cc(const arma::vec& y_vector, const arma::mat& model_matrix, const arma::vec& id_vector, const arma::vec& repeated_vector, const arma::vec& weights_vector, const char* link, const char* family, const arma::vec& mu_vector, const arma::vec& eta_vector, const char* correlation_structure, const arma::vec& alpha_vector, const double& phi);
RcppExport SEXP _geer_estimating_equations_gee_cc(SEXP y_vectorSEXP, SEXP model_matrixSEXP, SEXP id_vectorSEXP, SEXP repeated_vectorSEXP, SEXP weights_vectorSEXP, SEXP linkSEXP, SEXP familySEXP, SEXP mu_vectorSEXP, SEXP eta_vectorSEXP, SEXP correlation_structureSEXP, SEXP alpha_vectorSEXP, SEXP phiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y_vector(y_vectorSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type model_matrix(model_matrixSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type id_vector(id_vectorSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type repeated_vector(repeated_vectorSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weights_vector(weights_vectorSEXP);
    Rcpp::traits::input_parameter< const char* >::type link(linkSEXP);
    Rcpp::traits::input_parameter< const char* >::type family(familySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mu_vector(mu_vectorSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type eta_vector(eta_vectorSEXP);
    Rcpp::traits::input_parameter< const char* >::type correlation_structure(correlation_structureSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type alpha_vector(alpha_vectorSEXP);
    Rcpp::traits::input_parameter< const double& >::type phi(phiSEXP);
    rcpp_result_gen = Rcpp::wrap(estimating_equations_gee_cc(y_vector, model_matrix, id_vector, repeated_vector, weights_vector, link, family, mu_vector, eta_vector, correlation_structure, alpha_vector, phi));
    return rcpp_result_gen;
END_RCPP
}
// estimating_equations_gee_or
arma::vec estimating_equations_gee_or(const arma::vec& y_vector, const arma::mat& model_matrix, const arma::vec& id_vector, const arma::vec& repeated_vector, const arma::vec& weights_vector, const char* link, const arma::vec& mu_vector, const arma::vec& eta_vector, const arma::vec& alpha_vector);
RcppExport SEXP _geer_estimating_equations_gee_or(SEXP y_vectorSEXP, SEXP model_matrixSEXP, SEXP id_vectorSEXP, SEXP repeated_vectorSEXP, SEXP weights_vectorSEXP, SEXP linkSEXP, SEXP mu_vectorSEXP, SEXP eta_vectorSEXP, SEXP alpha_vectorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y_vector(y_vectorSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type model_matrix(model_matrixSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type id_vector(id_vectorSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type repeated_vector(repeated_vectorSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weights_vector(weights_vectorSEXP);
    Rcpp::traits::input_parameter< const char* >::type link(linkSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mu_vector(mu_vectorSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type eta_vector(eta_vectorSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type alpha_vector(alpha_vectorSEXP);
    rcpp_result_gen = Rcpp::wrap(estimating_equations_gee_or(y_vector, model_matrix, id_vector, repeated_vector, weights_vector, link, mu_vector, eta_vector, alpha_vector));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_geer_get_covariance_matrices_cc", (DL_FUNC) &_geer_get_covariance_matrices_cc, 12},
    {"_geer_get_covariance_matrices_or", (DL_FUNC) &_geer_get_covariance_matrices_or, 9},
    {"_geer_fit_geesolver_cc", (DL_FUNC) &_geer_fit_geesolver_cc, 22},
    {"_geer_fit_bingee_or", (DL_FUNC) &_geer_fit_bingee_or, 15},
    {"_geer_get_naive_matrix_inverse_independence", (DL_FUNC) &_geer_get_naive_matrix_inverse_independence, 9},
    {"_geer_get_gee_criteria_sc_cw", (DL_FUNC) &_geer_get_gee_criteria_sc_cw, 9},
    {"_geer_get_gee_criteria_sc_cw_or", (DL_FUNC) &_geer_get_gee_criteria_sc_cw_or, 6},
    {"_geer_get_pearson_residuals", (DL_FUNC) &_geer_get_pearson_residuals, 4},
    {"_geer_get_correlation_matrix", (DL_FUNC) &_geer_get_correlation_matrix, 3},
    {"_geer_get_marginalized_odds_ratios", (DL_FUNC) &_geer_get_marginalized_odds_ratios, 6},
    {"_geer_estimating_equations_gee_cc", (DL_FUNC) &_geer_estimating_equations_gee_cc, 12},
    {"_geer_estimating_equations_gee_or", (DL_FUNC) &_geer_estimating_equations_gee_or, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_geer(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
