# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_covariance_matrices <- function(y_vector, model_matrix, id_vector, repeated_vector, link, family, mu_vector, eta_vector, correlation_structure, alpha_vector, phi, weights_vector) {
    .Call(`_geer_get_covariance_matrices`, y_vector, model_matrix, id_vector, repeated_vector, link, family, mu_vector, eta_vector, correlation_structure, alpha_vector, phi, weights_vector)
}

get_covariance_matrices_or <- function(y_vector, model_matrix, id_vector, repeated_vector, link, mu_vector, eta_vector, alpha_vector, weights_vector) {
    .Call(`_geer_get_covariance_matrices_or`, y_vector, model_matrix, id_vector, repeated_vector, link, mu_vector, eta_vector, alpha_vector, weights_vector)
}

fit_geesolver <- function(y_vector, model_matrix, id_vector, repeated_vector, link, family, beta_vector, correlation_structure, mdependence, use_params, maxiter, tolerance, offset, phi, phi_fixed, alpha_vector, alpha_fixed, type, weights_vector, step_maxiter, step_multiplier, jeffreys_power) {
    .Call(`_geer_fit_geesolver`, y_vector, model_matrix, id_vector, repeated_vector, link, family, beta_vector, correlation_structure, mdependence, use_params, maxiter, tolerance, offset, phi, phi_fixed, alpha_vector, alpha_fixed, type, weights_vector, step_maxiter, step_multiplier, jeffreys_power)
}

fit_bingee_or <- function(y_vector, model_matrix, id_vector, repeated_vector, link, beta_vector, maxiter, tolerance, offset, alpha_vector, type, weight_vector, step_maxiter, step_multiplier, jeffreys_power) {
    .Call(`_geer_fit_bingee_or`, y_vector, model_matrix, id_vector, repeated_vector, link, beta_vector, maxiter, tolerance, offset, alpha_vector, type, weight_vector, step_maxiter, step_multiplier, jeffreys_power)
}

get_naive_matrix_inverse_independence <- function(y_vector, model_matrix, id_vector, link, family, mu_vector, eta_vector, phi) {
    .Call(`_geer_get_naive_matrix_inverse_independence`, y_vector, model_matrix, id_vector, link, family, mu_vector, eta_vector, phi)
}

get_gee_criteria_sc_cw <- function(y_vector, id_vector, repeated_vector, family, mu_vector, correlation_structure, alpha_vector, phi, weights_vector) {
    .Call(`_geer_get_gee_criteria_sc_cw`, y_vector, id_vector, repeated_vector, family, mu_vector, correlation_structure, alpha_vector, phi, weights_vector)
}

get_gee_criteria_sc_cw_or <- function(y_vector, id_vector, repeated_vector, mu_vector, alpha_vector, weights_vector) {
    .Call(`_geer_get_gee_criteria_sc_cw_or`, y_vector, id_vector, repeated_vector, mu_vector, alpha_vector, weights_vector)
}

arma2vec <- function(x) {
    .Call(`_geer_arma2vec`, x)
}

vec2arma <- function(x) {
    .Call(`_geer_vec2arma`, x)
}

linkfun_rcpp <- function(link, mu_vector) {
    .Call(`_geer_linkfun_rcpp`, link, mu_vector)
}

linkfun <- function(link, mu_vector) {
    .Call(`_geer_linkfun`, link, mu_vector)
}

linkinv_rcpp <- function(link, eta_vector) {
    .Call(`_geer_linkinv_rcpp`, link, eta_vector)
}

linkinv <- function(link, eta_vector) {
    .Call(`_geer_linkinv`, link, eta_vector)
}

mueta_rcpp <- function(link, eta_vector) {
    .Call(`_geer_mueta_rcpp`, link, eta_vector)
}

mueta <- function(link, eta_vector) {
    .Call(`_geer_mueta`, link, eta_vector)
}

mueta2_rcpp <- function(link, eta_vector) {
    .Call(`_geer_mueta2_rcpp`, link, eta_vector)
}

mueta2 <- function(link, eta_vector) {
    .Call(`_geer_mueta2`, link, eta_vector)
}

mueta3_rcpp <- function(link, eta_vector) {
    .Call(`_geer_mueta3_rcpp`, link, eta_vector)
}

mueta3 <- function(link, eta_vector) {
    .Call(`_geer_mueta3`, link, eta_vector)
}

valideta <- function(link, eta_vector) {
    .Call(`_geer_valideta`, link, eta_vector)
}

validmu <- function(family, mu_vector) {
    .Call(`_geer_validmu`, family, mu_vector)
}

get_phi_hat <- function(pearson_residuals_vector, params_no) {
    .Call(`_geer_get_phi_hat`, pearson_residuals_vector, params_no)
}

alpha_hat_exchangeable <- function(pearson_residuals_vector, id_vector, phi, params_no) {
    .Call(`_geer_alpha_hat_exchangeable`, pearson_residuals_vector, id_vector, phi, params_no)
}

alpha_hat_ar1 <- function(pearson_residuals_vector, id_vector, repeated_vector, phi, params_no) {
    .Call(`_geer_alpha_hat_ar1`, pearson_residuals_vector, id_vector, repeated_vector, phi, params_no)
}

alpha_hat_unstructured <- function(pearson_residuals_vector, id_vector, repeated_vector, phi, params_no) {
    .Call(`_geer_alpha_hat_unstructured`, pearson_residuals_vector, id_vector, repeated_vector, phi, params_no)
}

alpha_hat_mdependent <- function(pearson_residuals_vector, id_vector, repeated_vector, phi, params_no, mdependence) {
    .Call(`_geer_alpha_hat_mdependent`, pearson_residuals_vector, id_vector, repeated_vector, phi, params_no, mdependence)
}

alpha_hat_toeplitz <- function(pearson_residuals_vector, id_vector, repeated_vector, phi, params_no) {
    .Call(`_geer_alpha_hat_toeplitz`, pearson_residuals_vector, id_vector, repeated_vector, phi, params_no)
}

get_alpha_hat <- function(correlation_structure, pearson_residuals_vector, id_vector, repeated_vector, phi, params_no, mdependence) {
    .Call(`_geer_get_alpha_hat`, correlation_structure, pearson_residuals_vector, id_vector, repeated_vector, phi, params_no, mdependence)
}

correlation_independence <- function(dimension) {
    .Call(`_geer_correlation_independence`, dimension)
}

correlation_exchangeable <- function(alpha_vector, dimension) {
    .Call(`_geer_correlation_exchangeable`, alpha_vector, dimension)
}

correlation_exchangeable_inverse <- function(alpha_vector, dimension) {
    .Call(`_geer_correlation_exchangeable_inverse`, alpha_vector, dimension)
}

correlation_ar1 <- function(alpha_vector, dimension) {
    .Call(`_geer_correlation_ar1`, alpha_vector, dimension)
}

correlation_ar1_inverse <- function(alpha_vector, dimension) {
    .Call(`_geer_correlation_ar1_inverse`, alpha_vector, dimension)
}

correlation_mdependent <- function(alpha_vector, dimension) {
    .Call(`_geer_correlation_mdependent`, alpha_vector, dimension)
}

correlation_toeplitz <- function(alpha_vector) {
    .Call(`_geer_correlation_toeplitz`, alpha_vector)
}

correlation_unstructured <- function(alpha_vector, dimension) {
    .Call(`_geer_correlation_unstructured`, alpha_vector, dimension)
}

get_correlation_matrix <- function(correlation_structure, alpha_vector, dimension) {
    .Call(`_geer_get_correlation_matrix`, correlation_structure, alpha_vector, dimension)
}

get_correlation_matrix_inverse <- function(correlation_structure, alpha_vector, dimension) {
    .Call(`_geer_get_correlation_matrix_inverse`, correlation_structure, alpha_vector, dimension)
}

get_pearson_residuals <- function(family, y_vector, mu_vector) {
    .Call(`_geer_get_pearson_residuals`, family, y_vector, mu_vector)
}

get_weight_matrix_inverse <- function(family, mu_vector, repeated_vector, phi, cor_matrix_inverse, weights_vector) {
    .Call(`_geer_get_weight_matrix_inverse`, family, mu_vector, repeated_vector, phi, cor_matrix_inverse, weights_vector)
}

get_marginalized_odds_ratios <- function(response_vector, id_vector, repeated_vector, adding_constant, or_structure) {
    .Call(`_geer_get_marginalized_odds_ratios`, response_vector, id_vector, repeated_vector, adding_constant, or_structure)
}

get_subject_specific_odds_ratios <- function(repeated_vector_i, cluster_size_max, odds_ratios_vector) {
    .Call(`_geer_get_subject_specific_odds_ratios`, repeated_vector_i, cluster_size_max, odds_ratios_vector)
}

get_bivariate_distribution <- function(row_prob, col_prob, odds_ratio) {
    .Call(`_geer_get_bivariate_distribution`, row_prob, col_prob, odds_ratio)
}

get_v_matrix_or <- function(mu_vector, odds_ratios_vector, weights_vector) {
    .Call(`_geer_get_v_matrix_or`, mu_vector, odds_ratios_vector, weights_vector)
}

get_v_matrix_inverse_or <- function(mu_vector, odds_ratios_vector, weights_vector) {
    .Call(`_geer_get_v_matrix_inverse_or`, mu_vector, odds_ratios_vector, weights_vector)
}

get_bivariate_distribution_murow <- function(row_prob, col_prob, odds_ratio) {
    .Call(`_geer_get_bivariate_distribution_murow`, row_prob, col_prob, odds_ratio)
}

get_bivariate_distribution_murow2 <- function(row_prob, col_prob, odds_ratio) {
    .Call(`_geer_get_bivariate_distribution_murow2`, row_prob, col_prob, odds_ratio)
}

get_bivariate_distribution_murowcol <- function(row_prob, col_prob, odds_ratio) {
    .Call(`_geer_get_bivariate_distribution_murowcol`, row_prob, col_prob, odds_ratio)
}

get_g_matrix <- function(mu_vector, odds_ratios_vector) {
    .Call(`_geer_get_g_matrix`, mu_vector, odds_ratios_vector)
}

get_bivariate_distribution_mu <- function(mu_vector, odds_ratios_vector) {
    .Call(`_geer_get_bivariate_distribution_mu`, mu_vector, odds_ratios_vector)
}

get_g_matrix_mu <- function(mu_vector, odds_ratios_vector) {
    .Call(`_geer_get_g_matrix_mu`, mu_vector, odds_ratios_vector)
}

get_v_matrix_mu_or <- function(mu_vector, odds_ratios_vector, weights_vector) {
    .Call(`_geer_get_v_matrix_mu_or`, mu_vector, odds_ratios_vector, weights_vector)
}

estimating_equations_gee <- function(y_vector, model_matrix, id_vector, repeated_vector, link, family, beta_vector, mu_vector, eta_vector, correlation_structure, alpha_vector, phi, weights_vector) {
    .Call(`_geer_estimating_equations_gee`, y_vector, model_matrix, id_vector, repeated_vector, link, family, beta_vector, mu_vector, eta_vector, correlation_structure, alpha_vector, phi, weights_vector)
}

estimating_equations_gee_or <- function(y_vector, model_matrix, id_vector, repeated_vector, link, beta_vector, mu_vector, eta_vector, alpha_vector, weights_vector) {
    .Call(`_geer_estimating_equations_gee_or`, y_vector, model_matrix, id_vector, repeated_vector, link, beta_vector, mu_vector, eta_vector, alpha_vector, weights_vector)
}

update_beta_gee <- function(y_vector, model_matrix, id_vector, repeated_vector, link, family, beta_vector, mu_vector, eta_vector, correlation_structure, alpha_vector, phi, weights_vector) {
    .Call(`_geer_update_beta_gee`, y_vector, model_matrix, id_vector, repeated_vector, link, family, beta_vector, mu_vector, eta_vector, correlation_structure, alpha_vector, phi, weights_vector)
}

update_beta_naive <- function(y_vector, model_matrix, id_vector, repeated_vector, link, family, beta_vector, mu_vector, eta_vector, correlation_structure, alpha_vector, phi, weights_vector) {
    .Call(`_geer_update_beta_naive`, y_vector, model_matrix, id_vector, repeated_vector, link, family, beta_vector, mu_vector, eta_vector, correlation_structure, alpha_vector, phi, weights_vector)
}

update_beta_robust <- function(y_vector, model_matrix, id_vector, repeated_vector, link, family, beta_vector, mu_vector, eta_vector, correlation_structure, alpha_vector, phi, weights_vector) {
    .Call(`_geer_update_beta_robust`, y_vector, model_matrix, id_vector, repeated_vector, link, family, beta_vector, mu_vector, eta_vector, correlation_structure, alpha_vector, phi, weights_vector)
}

update_beta_empirical <- function(y_vector, model_matrix, id_vector, repeated_vector, link, family, beta_vector, mu_vector, eta_vector, correlation_structure, alpha_vector, phi, weights_vector) {
    .Call(`_geer_update_beta_empirical`, y_vector, model_matrix, id_vector, repeated_vector, link, family, beta_vector, mu_vector, eta_vector, correlation_structure, alpha_vector, phi, weights_vector)
}

update_beta_jeffreys <- function(y_vector, model_matrix, id_vector, repeated_vector, link, family, beta_vector, mu_vector, eta_vector, correlation_structure, alpha_vector, phi, weights_vector, jeffreys_power) {
    .Call(`_geer_update_beta_jeffreys`, y_vector, model_matrix, id_vector, repeated_vector, link, family, beta_vector, mu_vector, eta_vector, correlation_structure, alpha_vector, phi, weights_vector, jeffreys_power)
}

update_beta <- function(y_vector, model_matrix, id_vector, repeated_vector, link, family, beta_vector, mu_vector, eta_vector, correlation_structure, alpha_vector, phi, type, weights_vector, jeffreys_power) {
    .Call(`_geer_update_beta`, y_vector, model_matrix, id_vector, repeated_vector, link, family, beta_vector, mu_vector, eta_vector, correlation_structure, alpha_vector, phi, type, weights_vector, jeffreys_power)
}

update_beta_gee_or <- function(y_vector, model_matrix, id_vector, repeated_vector, link, beta_vector, mu_vector, eta_vector, alpha_vector, weights_vector) {
    .Call(`_geer_update_beta_gee_or`, y_vector, model_matrix, id_vector, repeated_vector, link, beta_vector, mu_vector, eta_vector, alpha_vector, weights_vector)
}

update_beta_naive_or <- function(y_vector, model_matrix, id_vector, repeated_vector, link, beta_vector, mu_vector, eta_vector, alpha_vector, weights_vector) {
    .Call(`_geer_update_beta_naive_or`, y_vector, model_matrix, id_vector, repeated_vector, link, beta_vector, mu_vector, eta_vector, alpha_vector, weights_vector)
}

update_beta_robust_or <- function(y_vector, model_matrix, id_vector, repeated_vector, link, beta_vector, mu_vector, eta_vector, alpha_vector, weights_vector) {
    .Call(`_geer_update_beta_robust_or`, y_vector, model_matrix, id_vector, repeated_vector, link, beta_vector, mu_vector, eta_vector, alpha_vector, weights_vector)
}

update_beta_empirical_or <- function(y_vector, model_matrix, id_vector, repeated_vector, link, beta_vector, mu_vector, eta_vector, alpha_vector, weights_vector) {
    .Call(`_geer_update_beta_empirical_or`, y_vector, model_matrix, id_vector, repeated_vector, link, beta_vector, mu_vector, eta_vector, alpha_vector, weights_vector)
}

update_beta_jeffreys_or <- function(y_vector, model_matrix, id_vector, repeated_vector, link, beta_vector, mu_vector, eta_vector, alpha_vector, weights_vector, jeffreys_power) {
    .Call(`_geer_update_beta_jeffreys_or`, y_vector, model_matrix, id_vector, repeated_vector, link, beta_vector, mu_vector, eta_vector, alpha_vector, weights_vector, jeffreys_power)
}

update_beta_or <- function(y_vector, model_matrix, id_vector, repeated_vector, link, beta_vector, mu_vector, eta_vector, alpha_vector, type, weights_vector, jeffreys_power) {
    .Call(`_geer_update_beta_or`, y_vector, model_matrix, id_vector, repeated_vector, link, beta_vector, mu_vector, eta_vector, alpha_vector, type, weights_vector, jeffreys_power)
}

subset_matrix <- function(x, y) {
    .Call(`_geer_subset_matrix`, x, y)
}

kappa_matrix <- function(dimension) {
    .Call(`_geer_kappa_matrix`, dimension)
}

kronecker_sum_same <- function(x) {
    .Call(`_geer_kronecker_sum_same`, x)
}

kronecker_left_identity_kappa <- function(x) {
    .Call(`_geer_kronecker_left_identity_kappa`, x)
}

kronecker_identity_right_kappa <- function(x) {
    .Call(`_geer_kronecker_identity_right_kappa`, x)
}

kappa_right <- function(x) {
    .Call(`_geer_kappa_right`, x)
}

kronecker_vector_identity <- function(x) {
    .Call(`_geer_kronecker_vector_identity`, x)
}

kronecker_vector_matrix <- function(x, y) {
    .Call(`_geer_kronecker_vector_matrix`, x, y)
}

kronecker_rcpp <- function(x, y) {
    .Call(`_geer_kronecker_rcpp`, x, y)
}

variance <- function(family, mu_vector) {
    .Call(`_geer_variance`, family, mu_vector)
}

variancemu <- function(family, mu_vector) {
    .Call(`_geer_variancemu`, family, mu_vector)
}

variancemu2 <- function(family, mu_vector) {
    .Call(`_geer_variancemu2`, family, mu_vector)
}

